version: '3.4'

services:
  catalogdb:
    container_name: shopping-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
