version: '3.4'

services:
  catalogdb:
    container_name: shopping-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redisdb:
    container_name: shopping-basket
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data/db
  portainer:
    container_name: portainer
    ports:
      - "8080:8000" 
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  mongolient:
    container_name: mongolient
    ports:
      - "3000:3000" 
  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb

  basket.api:
    container_name: basker.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "redisconnectionstring:ConnectionStrings=redisdb:6379"
    ports:
      - "8001:80"
    depends_on:
      - redisdb
